// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_BluetoothManager.cpp"
#include "EWIEGA46WW/moc_basic_func.cpp"
#include "EWIEGA46WW/moc_music_player.cpp"
#include "EWIEGA46WW/moc_weather_provider.cpp"
